* Cled 

** examples

# playing with a file
#+begin_src common-lisp
(ql:quickload "cled")
(in-package 'cled)
(load-file) ;; ./rope.py
(getf (cled::get-buffer (cled::where :name "rope.py")) :name) ;; "rope.py"
(nth 1 (getf (cled::get-buffer (cled::where :name "rope.py")) :contents)) ;; "# Python program to concatenate two strings using"
#+end_src

# update and save a line
#+begin_src common-lisp
(cled::load-file) ;;./rope.py
(setf (nth 1 (getf (cled::get-buffer (cled::where :name "rope.py")) :contents)) "#this is a test")
(cled::write-contents (cled::get-buffer (cled::where :name "rope.py")))

;; OR

(cled::load-file) ;;./rope.py
(cled::update-buffer-line (cled::get-buffer (cled::where :name "rope.py")) :line 3 :write t)  ;; input line from user

;; OR 

(cled::load-file) ;;./rope.py
(cled::update-buffer-line (cled::get-buffer (cled::where :name "rope.py")) :line 3 :content "write content here" :write t)

#+end_src

# NOTE: :line 3 will edit line #4 because 0 indexing

** Usage

** Installation

** MVP

OK so I think I want a terminal ed style editor that will connect to my central server, then edit files, push and pull clients.
- [ ] Terminal ed style editor
  - [ ] Should be lightweight, cross platform and easy to install.
  - [ ] Should be able to connect to a central server.
  - [ ] Should be able to run locally without server connection.
  - [ ] Should be able to run at least system emacs commands from one client to another.
  - [ ] Should have a command to be able to run a websocket client

- client services
  - [ ] Pull a file to server/a connected client
  - [ ] Push a file to server/a connected client
  - [ ] Edit a file on server
  - [ ] Add a file to server
  - [ ] Delete a file to server

- [ ] Server
  - [ ] A http server to call apon to the server ed style editor.
  - [ ] A websocket service to call disbatch client editor commands to the remote client.

    
** TODO features

- [ ] CLI
- [ ] eval common lisp
- [ ] eval common lisp on line
- [ ] set current buffer
- [ ] lock file? or at least optional update file on external change
- [ ] switch buffers
- [ ] regex?
- [ ] init file with custom functions
- [ ] hooks (for saving & loading)
- [ ] major modes?
- [ ] line editing
  - find & replace
  
